- name: PHP - uprade all packages first
  ansible.builtin.apt:
    update_cache: true
    state: latest
    upgrade: true

- name: PHP - install php and modules php8.2-fpm php8.2-gd php8.2-mysql ... imagemagick libmagickcore-6.q16-6-extra
  ansible.builtin.apt:
    update_cache: true
    state: latest
    name:
      - php8.2-fpm
      - php8.2-gd
      - php8.2-mysql
      - php8.2-curl
      - php8.2-xml
      - php8.2-zip
      - php8.2-intl
      - php8.2-mbstring
      - php8.2-bz2
      - php-json
      - php8.2-apcu
      - php8.2-imagick
      - php8.2-gmp
      - php8.2-bcmath
      - imagemagick
      - libmagickcore-6.q16-6-extra

- name: PHP - restart php-fpm
  ansible.builtin.systemd:
    name: php8.2-fpm
    state: restarted
